### PR TITLE
Updated Redis cache project to support .NET Core

### PR DESCRIPTION
**Pull request by kichalla**
@muratg @Eilon @Tratcher

### CODE REVIEW

**Comment by Tratcher** [comment]
@muratg are we finally getting an RTM version of stackechange.redis?

**Comment by Tratcher** [comment]
https://github.com/aspnet/Caching/pull/147/files

**Comment by Tratcher** [comment]
https://github.com/aspnet/Caching/issues/121

**Comment by muratg** [comment]
:shipit:

**Comment by kichalla** [comment]
@muratg Yes I am hitting the issue(`localhost`) now on my Linux VM

image

**Comment by muratg** [comment]
@kichalla OK, thanks.

@glennc Let us know if you'd like to check this in still. Keep in mind that we may need to pull it out if StackExchange.Redis does not RTM before us.

**Comment by muratg** [comment]
Had an offline discussion with @glennc and decided to go forward with pushing this to have the package on the dev feeds. If we don't get a StackExchange.Redis RTM package close to RTM, we'll pull this back.

**Comment by RehanSaeed** [comment]
Is this getting pushed to NuGet any time soon?

**Comment by muratg** [comment]
@RehanSaeed mainly myget for now. I expect this to be on nuget with the rest of 1.1 release.

**Pull request merged**
