### PR TITLE
Replace ci-dev feed with dev feed.

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by natemcmaster** [comment]
Can you also update LineupPackageRestoreSource in repo.props?

**Comment by pranavkm** [comment]
Sure. But what's it used for these days?

**Comment by natemcmaster** [comment]
It provides the default value for `run upgrade deps`. See [this target](https://github.com/aspnet/BuildTools/blob/2f3856d2ba4f659fcb9253215b83946a06794a27/modules/KoreBuild.Tasks/module.targets#L53-L62)

**Comment by pranavkm** [comment]
🆙 📅 

Using this as a template for bulk update.

**Comment by natemcmaster** [comment]
Looks like these packages aren't on aspnetcore-dev yet.

**Pull request closed without merging**
