### PR TITLE
Add Caching SqlConfig tool to sample

### PR DESCRIPTION
**Pull request by BrennanConroy**
#186 
@troydai

### CODE REVIEW

**Comment by Tratcher** [comment]
Isn't there an issue with tools that prevents them from being used as project references? e.g. in the same repo. @moozzyk

**Comment by moozzyk** [comment]
Yes. Project to Project references don't work for tools so not sure how you were able to run this. A workaround might be to add a global.json file in the samples folder which will prevent from bringing the tool as project.

**Comment by BrennanConroy** [comment]
Well wouldn't it just download it from myget...

**Comment by moozzyk** [comment]
You can try it (but it did not work in other repos...)

**Comment by BrennanConroy** [comment]
When I ran it that's what it looked like it was doing

**Comment by BrennanConroy** [comment]
Whats up with this?

**Comment by troydai** [comment]
LGTM

**Comment by moozzyk** [comment]
My understanding is that it should not work because of https://github.com/dotnet/cli/issues/1215. I wonder if it might have worked because you had the package cached?

**Comment by BrennanConroy** [comment]
Deleted cache and it still works fine.

**Comment by Tratcher** [comment]
It's still resolving as a package reference, not a project reference, right?

**Comment by BrennanConroy** [comment]
Yeah

**Comment by moozzyk** [comment]
That's why this works. Not sure why it is not resolved as a project reference.

**Comment by muratg** [comment]
@BrennanConroy What's the latest with this?

**Comment by BrennanConroy** [comment]
I can merge this, but its weird because the tool restores from your configured feeds and not as a project reference, there is a CLI issue logged for that

**Comment by muratg** [comment]
@BrennanConroy What's the CLI bug?

**Comment by BrennanConroy** [comment]
https://github.com/dotnet/cli/issues/1215

**Comment by muratg** [comment]
OK, it looks like they backlogged the bug. I'm backlogging this one as well.

**Pull request closed without merging**
