### PR TITLE
Update sample project's framework dependencies to dotnet.

### PR DESCRIPTION
**Pull request by CatPhat**
Resolves missing dependency issues with the sample project's project.json file.

### CODE REVIEW

**Comment by Tratcher** [comment]
@anurse ??

**Comment by anurse** [comment]
Applications, samples included, should not be using `dotnet`.

**Comment by CatPhat** [comment]
Ah sorry, had assumed that ```dotnet```  was now being used due to the references in the other ```Microsoft.Framework.Caching.*``` projects.

**Comment by anurse** [comment]
No problem :). It's not fully documented yet so I can totally understand the confusion! We'll have more detailed docs out soon, but `dotnet` should generally be used in Class Libraries, and not in code that is directly executed (so, Web/Console Apps, Unit Tests, etc.)

**Comment by Tratcher** [comment]
@anurse How did we decide which projects to convert? I see that Caching, Logging, and EF were changed, but not HttpAbstractions, Hosting, or DNX. Or have we just not gotten around to it?

**Comment by anurse** [comment]
Things that are tied to the DNX application model should not be converted either. `dotnet` is for things that would previously have been "portable class libraries"

**Pull request closed without merging**
