### PR TITLE
Remove direct Microsoft.NETCore.Platforms dependency.

### PR DESCRIPTION
**Pull request by NTaylorMullen**
- Microsoft.NETCore.App now pulls this package in.

aspnet/Coherence-Signed#344

/cc @muratg

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
:shipit: Are you doing this for all repos?

**Comment by NTaylorMullen** [comment]
@JunTaoLuo Yes, the others will not have a PR though. Doing a dry run here as @muratg suggested.

**Comment by muratg** [comment]
:shipit:

**Comment by NTaylorMullen** [comment]
Has a few blocking issues to do this across the board. Mostly just waiting for https://github.com/dotnet/cli/issues/3415 to be fixed.

**Pull request closed without merging**
