### PR TITLE
MongoDB implementation

### PR DESCRIPTION
**Pull request by sunsided**
I created a MongoDB implementation, basically a variant of the Redis one. Is this useful for anyone?

Sample works, tests are basically a shot in the dark; the test runner seems to require a runtime version I don't have access to at the moment. I couldn't figure out how to map the Redis CI approach to this one, process finding and all.

### CODE REVIEW

**Comment by davidfowl** [comment]
Awesome, this isnt something we'd maintain and support ourselves. This would be better suited for a contrib repository https://github.com/aspnet-contrib

**Comment by sunsided** [comment]
Sounds good. Where would I start? :)

**Comment by davidfowl** [comment]
@PinpointTownes do you know who owns https://github.com/aspnet-contrib?

**Comment by PinpointTownes** [comment]
@davidfowl yup... it's me :smile:

**Comment by davidfowl** [comment]
You guys can work something out :smile:

**Comment by sunsided** [comment]
@PinpointTownes I sent you a mail. :grimacing:

**Pull request closed without merging**
