### PR TITLE
Removed Connect method from IDistributedCache

### PR DESCRIPTION
**Pull request by kichalla**
This change is going to need changes in other repos, for example Session which calls the `Connect` method.

### CODE REVIEW

**Comment by kichalla** [comment]
cc @lodejard @muratg @Tratcher

**Comment by muratg** [comment]
LGTM

**Comment by Tratcher** [comment]
Will you also be removing ISessionStore.Connect? This will move the cache initialization from startup (https://github.com/aspnet/Session/blob/e91ce99c70614efab26825f685dd026e721b0fa0/src/Microsoft.AspNet.Session/SessionMiddleware.cs#L65) to first access and make issues harder to debug.

**Comment by Tratcher** [comment]
Rebased and merged.

**Pull request closed without merging**
