### PR TITLE
Fix package metadata

### PR DESCRIPTION
**Pull request by Eilon**
@ajaybhargavb @Tratcher

### CODE REVIEW

**Comment by Eilon** [comment]
Note that I dropped "ASP.NET" from the package metadata because these are not specific to ASP.NET.

**Comment by ajaybhargavb** [comment]
:shipit:

**Comment by Eilon** [comment]
Well, good evening! And thanks :smile:

**Comment by Eilon** [comment]
https://github.com/aspnet/Caching/commit/6f5cb6c7fea3aabd94990b38f5bae33091de7e24

**Pull request closed without merging**
