### PR TITLE
Disable test that fails on Mono.

### PR DESCRIPTION
**Pull request by cesarbs**
cc @Tratcher @JunTaoLuo

### CODE REVIEW

**Comment by Tratcher** [comment]
Mono or CoreClr?

**Comment by JunTaoLuo** [comment]
I think the test should be disabled on Mono only since it's only failing on travis. The Mac CoreCLR tests are all passing.

**Comment by cesarbs** [comment]
@JunTaoLuo Yeah, I had to make a choice. I went with OS X since it only fails on Mono on OS X. But disabling it on Mono makes more sense, otherwise we lose CoreCLR coverage on Mac.

**Comment by cesarbs** [comment]
What's really weird about this is that the other test in the same class, which relies on the exact same behavior (i.e. a finalizer being called in order to invoke a callback), passes. Beats me.

**Comment by cesarbs** [comment]
Disabled on Mono.

**Comment by Tratcher** [comment]
:shipit:

**Comment by JunTaoLuo** [comment]
:shipit: Maybe file an issue to fix this in the future?

**Pull request merged**
