### PR TITLE
Remove System.Threading.ThreadPool dependency

### PR DESCRIPTION
**Pull request by bricelam**
It prevented the package from installing on UWP projects.

@rowanmiller @natemcmaster

### CODE REVIEW

**Comment by Tratcher** [comment]
Can you do it without creating closures?

**Comment by bricelam** [comment]
@Tratcher What's the concern? It was passing the state around before using some internal mechanism...

**Comment by davidfowl** [comment]
To avoid the memory allocation.

**Comment by bricelam** [comment]
It's potentially allocating *less* memory than before. QueuUserWorkItem does this:
```C#
var tpcallBack = new QueueUserWorkItemCallback(callBack, state, compressStack, ref stackMark);
```

**Comment by bricelam** [comment]
Which is no different than a closure:
```
class Closure
{
    Action<object> _action;
    object _state;

    public Closure(Action<object> action, object state)
    {
        _action = action;
        _state = state;
    }

    public void Invoke() => _action(_state);
}
```

**Comment by bricelam** [comment]
Updated to use the framework's cached delegate.

**Comment by bricelam** [comment]
Closure removed.

**Comment by anpete** [comment]
:shipit:

**Comment by justinvp** [comment]
`Task.Run` should be used to avoid child tasks from attaching to the parent (or alternatively, use `Task.Factory.StartNew` but specify `DenyChildAttach` ([details](http://blogs.msdn.com/b/pfxteam/archive/2012/09/22/new-taskcreationoptions-and-taskcontinuationoptions-in-net-4-5.aspx)).

Also, the delegates are still being allocated each time the methods are called. The calls should be able to be written in a way such that the C# compiler will cache and reuse a single delegate instance.

I'll submit a PR with these changes.

**Pull request merged**
