### PR TITLE
Fix OSX build on Travis.

### PR DESCRIPTION
**Pull request by cesarbs**

### CODE REVIEW

**Comment by Tratcher** [comment]
What in Caching depends on OpenSsl? SQL?

**Comment by cesarbs** [comment]
It's not Caching itself. We need to perform those tests before installing dotnet in OSX: https://www.microsoft.com/net/core#macosx

**Comment by Tratcher** [comment]
Ah, so every repo needs this?

**Comment by cesarbs** [comment]
Yes.

**Pull request merged**
