### PR TITLE
Use Directory.Build.props/targets

### PR DESCRIPTION
**Pull request by natemcmaster**
Repeating a pattern we've begun using in MVC, Kestrel, Razor, and a few other repos.

FYI - I'd like to make the same change in the following low-traffic repos. If you're all okay with this, I'll do it without opening duplicate PRs. cc @Tratcher @pranavkm @ryanbrandenburg @mikeharder 

Repos:
 - DataProtection
 - Diagnostics
 - Hosting
 - HtmlAbstractions
 - HttpAbstractions
 - HttpSysServer
 - IISIntegration
 - Localization
 - Logging
 - Proxy
 - ResponseCaching
 - ServerTests
 - Session
 - StaticFiles
 - Testing
 - WebSockets

### CODE REVIEW

**Comment by mikeharder** [comment]
I'm fine with making this change, in addition to the lineups change, in low-traffic repos without getting PR approval.  If it's not too much work, it's nice to have a PR even if it was merged before being approved (as a more convenient way to review the change, add comments after merge, etc).

**Comment by mikeharder** [comment]
Meaning you could open a PR with no reviewers and just merge once Travis/AppVeyor pass, and anyone who cares can review later.

**Comment by natemcmaster** [comment]
>Meaning you could open a PR with no reviewers and just merge once Travis/AppVeyor pass, and anyone who cares can review later.

Ok, I can do that if it helps make the process cleaner. Waiting for PR signoff is typically the slowest part of doing changes like this that touch every repo.

**Comment by mikeharder** [comment]
If you think opening the PRs and waiting for Travis/AppVeyor is a waste of effort, I'm fine with skipping that as well.

**Comment by natemcmaster** [comment]
For some repos it's a waste of effort. e.g. Proxy and Session.  But it definitely depends on the repo. I didn't include Identity, Configuration, EF, SignalR, and a few others in my list above because I know there are devs working on them and should see the PR.

**Comment by natemcmaster** [comment]
I'm going to move forward with this then. Ping if you object.

**Pull request merged**
